apiVersion: v1
kind: Service
metadata:
  name: external-load-balancer
spec:
  selector:
    app: web-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-ingress
spec:
  ingressClassName: nginx  # or whatever the name of your IngressClass is
  rules:
  - http:
      paths:
      - path: /frontend
        pathType: Prefix
        backend:
          service:
            name: web-server-1
            port:
              number: 8080
      - path: /frontend
        pathType: Prefix
        backend:
          service:
            name: web-server-2
            port:
              number: 8080
      - path: /backend
        pathType: Prefix
        backend:
          service:
            name: web-server-2
            port:
              number: 8080
      - path: /backend
        pathType: Prefix
        backend:
          service:
            name: web-server-3
            port:
              number: 8080
      - path: /admin
        pathType: Prefix
        backend:
          service:
            name: web-server-3
            port:
              number: 8080
