apiVersion: v1
kind: Service
metadata:
  name: internal-db-load-balancer
spec:
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 3306  # Replace with your database port
      targetPort: 3306  # Replace with your database port
